---
Name: lognroutes
After: 'framework/routes#coreroutes'
---
Director:
  rules:
    'data//schoolsByCity': 'AjaxController'
    'data//universitySubmit': 'AjaxController'
    'data//submit': 'AjaxController'
    'data//requestUpdate': 'AjaxController'
    'data//addToNewsletter': 'AjaxController'
    'v': 'ActionsController'
    'uv': 'UniversityActionsController'
---